[package]
name = "advent-of-code-2025"
version = "0.1.0"
edition = "2024"


[dependencies]
wasm-bindgen = "0.2"

# For input downloading in non-WASM contexts
reqwest = { version = "0.11", features = ["blocking"] }
dotenv = "0.15.0"

[[bin]]
name = "advent-of-code-2025"
path = "src/main.rs"
bench = false

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"
bench = false
